### PR TITLE
Compatibility with gpiod 2.x

### PR DESCRIPTION
**Pull request by puddly**
Resetting the GPIO pin state after releasing the line is now apparently deprecated, as the new kernel API reverts the pins to an unknown "default" state after the last line request is released.

### CODE REVIEW

**Comment by darkxst** [comment]
> as the new kernel API reverts the pins to an unknown "default" state after the last line request is released.

I not so sure this is the case, I seem to get stuck in bootloader with this as is. 
```
python -m universal_silabs_flasher --device /dev/ttyS4 --bootloader-reset ihost probe
2023-12-20 23:43:40 a0d7b954-ssh universal_silabs_flasher.flasher[658] INFO Triggering ihost bootloader
2023-12-20 23:43:40 a0d7b954-ssh universal_silabs_flasher.flasher[658] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-12-20 23:43:40 a0d7b954-ssh universal_silabs_flasher.flasher[658] WARNING No application can be launched
2023-12-20 23:43:40 a0d7b954-ssh universal_silabs_flasher.flasher[658] INFO Detected bootloader version '1.A.3' (1.3)
2023-12-20 23:43:40 a0d7b954-ssh universal_silabs_flasher.flasher[658] INFO Detected ApplicationType.GECKO_BOOTLOADER, version '1.A.3' (1.3) at 115200 baudrate (bootloader baudrate 115200)
```

Adding a 4th pin state to reset both GPIO lines to True fixes it though.

**Comment by puddly** [comment]
gpiod 2.x is posing a *really* annoying problem right now that I'm unsure of how to solve:

1. It not providing binary wheels means that the flasher can't be `pip install`ed unless you have a full build environment set up.
2. We can pin `gpiod<2`, but Home Assistant OS already includes a wheel for gpiod 2. This would cause a dependency conflict.
3. We can't migrate to `setup.py` to dynamically compute dependencies (i.e. support both versions but install the pure-Python one if none is available) because Pyodide only works with wheels!

Possible solutions:

1. Support both versions and have the default package depend on `gpiod < 2` but also provide `universal-silabs-flasher[gpiod2]`. Problem: I don't think you can override dependencies in `pyproject.toml` like this using optional dependencies.
2. Manually distribute wheels with the web flasher so that we can downgrade back to `setup.py`. This may be difficult to accomplish but I think it's possible to make the web flasher entirely self-contained, without it actually downloading any packages from the internet.
3. Support both versions of gpiod in the package but depend explicitly on `gpiod < 2` in this package. It may be possible to have Home Assistant ignore the dependency conflict.

**Comment by puddly** [comment]
I'm pinning `gpiod==1.5.4` for now to ensure installation always works but breaking out GPIO communication to a separate module, to ensure compatibility with both versions of `gpiod`.

**Comment by darkxst** [comment]
> * Support both versions and have the default package depend on `gpiod < 2` but also provide `universal-silabs-flasher[gpiod2]`. Problem: I don't think you can override dependencies in `pyproject.toml` like this using optional dependencies.

This would probably only work in reverse to downgrade the dep i.e. `universal-silabls-flasher[gpiod1]`. Which is not particularly user friendly!

**Pull request merged**
