### PR TITLE
Fix infinite loop in CPC deserialization

### PR DESCRIPTION
**Pull request by puddly**
Found in https://github.com/NabuCasa/universal-silabs-flasher/pull/85/commits/f37bde18f4d6cccff988372b69345e3656b1dae3.

Ping @tl-sl

### CODE REVIEW

**Comment by darkxst** [comment]
This does not seem to be raising value error:

```
2024-11-06 10:50:41.545 xps1520 universal_silabs_flasher.cpc DEBUG Sending data b'\x14\x00\n\x00\xc4U\xd3\x02\x00\x04\x00\x03\x00\x00\x00\xdb\x12'
2024-11-06 10:50:41.553 xps1520 universal_silabs_flasher.cpc DEBUG Failed to parse buffer bytearray(b'\x14\r\nNo command found\n> \xc4U\xd3\x02\x04\x03\xdb\x12'): ValueError('Invalid header checksum')
```
First byte of the response from router cli happens to match `cpc_types.FLAG`. I suppose it must be echoing this back the sent command.

just for reference a normal response from router does echo command back:
```
universal_silabs_flasher.router DEBUG Parsing State.INFO: bytearray(b'version\r\nstack ver. [8.0.2 GA build 397]\r\n\r\n> ')
```

**Comment by puddly** [comment]
Hmm, that's different from what I thought the error was. Do you mean that with this patch, the infinite loop still happens?

**Comment by darkxst** [comment]
> Hmm, that's different from what I thought the error was. Do you mean that with this patch, the infinite loop still happens?

I hadnt noticed the echoed cpc bytes previously.
 
yes, it still hitting infinite loop in most cases. Occasionally a random log message is received that correctly triggers `ValueError` and `.clear()`. But for response to a command, it always starts with the cpc flag.

**Comment by puddly** [comment]
Can you disable the local echo?

```c
// <q SL_CLI_LOCAL_ECHO> Enable local echo
// <i> Default: 1
// <i> If enabled, what is written in the terminal will be echoed back, so the
// <i> user will see what is written.
#define SL_CLI_LOCAL_ECHO                  1
```

**Comment by darkxst** [comment]
sure, I will try.

**Comment by tl-sl** [comment]
ok, it works with local echo disabled.

**Pull request merged**
