### PR TITLE
Ensure flasher works on Windows

### PR DESCRIPTION
**Pull request by puddly**
The packages are all cross-platform so it should.

### CODE REVIEW

**Comment by MattWestb** [comment]
# Thanks !!!!
Fast test on my test system running Windows 10 and looks very good:
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> universal-silabs-flasher     --device com4     --bootloader-baudrate 115200     --baudrate 115200     flash     --firmware NabuCasa_SkyConnect_EZSP_v7.1.3.0_ncp-uart-hw_115200.gbl
2022-12-07 17:16:56 MW-E3222 universal_silabs_flasher.flash[10892] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.3'>, ezsp_version=<AwesomeVersion SimpleVer '7.1.3.0'>, fw_type=<FirmwareImageType.NCP_UART_HW: 'ncp-uart-hw'>)
2022-12-07 17:16:56 MW-E3222 universal_silabs_flasher.flasher[10892] INFO Probing ApplicationType.GECKO_BOOTLOADER
2022-12-07 17:16:58 MW-E3222 universal_silabs_flasher.flasher[10892] INFO Probing ApplicationType.CPC
2022-12-07 17:17:02 MW-E3222 universal_silabs_flasher.flasher[10892] INFO Probing ApplicationType.EZSP
2022-12-07 17:17:04 MW-E3222 universal_silabs_flasher.flasher[10892] INFO Detected ApplicationType.EZSP, version 7.0.2.0.406
2022-12-07 17:17:04 MW-E3222 universal_silabs_flasher.flash[10892] INFO Detected running firmware ApplicationType.EZSP, version 7.0.2.0.406
NabuCasa_SkyConnect_EZSP_v7.1.3.0_ncp-uart-hw_115200.gbl  [####################################]  100%
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> universal-silabs-flasher     --device com4     --bootloader-baudrate 115200     --baudrate 115200     flash     --firmware NabuCasa_SkyConnect_EZSP_v7.0.2.0_ncp-uart-hw_115200.gbl
2022-12-07 17:19:07 MW-E3222 universal_silabs_flasher.flasher[14824] INFO Probing ApplicationType.GECKO_BOOTLOADER
2022-12-07 17:19:09 MW-E3222 universal_silabs_flasher.flasher[14824] INFO Probing ApplicationType.CPC
2022-12-07 17:19:13 MW-E3222 universal_silabs_flasher.flasher[14824] INFO Probing ApplicationType.EZSP
2022-12-07 17:19:14 MW-E3222 universal_silabs_flasher.flasher[14824] INFO Detected ApplicationType.EZSP, version 7.1.3.0.342
2022-12-07 17:19:14 MW-E3222 universal_silabs_flasher.flash[14824] INFO Detected running firmware ApplicationType.EZSP, version 7.1.3.0.342
NabuCasa_SkyConnect_EZSP_v7.0.2.0_ncp-uart-hw_115200.gbl  [####################################]  100%
```
I need running EZSP protocol V8 then sniffing with `com.zsmartsystems.zigbee.sniffer` that is not supporting V9 so need one early 7. 0 for doing that :-)))

May i request the same fix for Bellows and Zigpy (CLI) so it also working on windows then accessing the comports ?
Current version is working OK with socket connected NCP but is having problems with windows native comports (the releasing of the comports is not working and is being in locked state).

Thanks in advance !!!

MW

**Comment by puddly** [comment]
Sure. When you say "the releasing of the comports is not working and is being in locked state", what happens? Does re-running the command fail with an access error?

**Comment by MattWestb** [comment]
Was trying bellows and its looks working OK ;-((
The key is setting the baud rate then its working OK.
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> bellows -d com4 -b 115200 info
[00:3c:84:ff:fe:92:bc:12]
[0xfffe]
[<EmberNetworkStatus.NO_NETWORK: 0>]
[<EmberStatus.NOT_JOINED: 147>, <EmberNodeType.UNKNOWN_DEVICE: 0>, EmberNetworkParameters(extendedPanId=00:00:00:00:00:00:00:00, panId=0x0000, radioTxPower=0, radioChannel=0, joinMethod=<EmberJoinMethod.USE_MAC_ASSOCIATION: 0>, nwkManagerId=0x0000, nwkUpdateId=0, channels=<Channels.NO_CHANNELS: 0>)]
[<EmberStatus.NOT_JOINED: 147>, EmberCurrentSecurityState(bitmask=<EmberCurrentSecurityBitmask.STANDARD_SECURITY_MODE: 0>, trustCenterLongAddress=2d:9d:20:00:2d:96:30:00)]
Manufacturer: Nabu Casa
Board name: SkyConnect v1.0
EmberZNet version: 7.0.2.0 build 406

(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> bellows -d com4 -b 115200 config -a
NOTE: Configuration changes do not persist across resets
CONFIG_PACKET_BUFFER_COUNT=255
CONFIG_NEIGHBOR_TABLE_SIZE=16
CONFIG_APS_UNICAST_MESSAGE_COUNT=10
CONFIG_BINDING_TABLE_SIZE=32
CONFIG_ADDRESS_TABLE_SIZE=8
CONFIG_MULTICAST_TABLE_SIZE=8
CONFIG_ROUTE_TABLE_SIZE=16
CONFIG_DISCOVERY_TABLE_SIZE=8
CONFIG_STACK_PROFILE=0
CONFIG_SECURITY_LEVEL=5
CONFIG_MAX_HOPS=30
CONFIG_MAX_END_DEVICE_CHILDREN=32
CONFIG_INDIRECT_TRANSMISSION_TIMEOUT=3000
CONFIG_END_DEVICE_POLL_TIMEOUT=8
CONFIG_TX_POWER_MODE=0
CONFIG_DISABLE_RELAY=0
CONFIG_TRUST_CENTER_ADDRESS_CACHE_SIZE=0
CONFIG_SOURCE_ROUTE_TABLE_SIZE=7
CONFIG_FRAGMENT_WINDOW_SIZE=1
CONFIG_FRAGMENT_DELAY_MS=0
CONFIG_KEY_TABLE_SIZE=12
CONFIG_APS_ACK_TIMEOUT=1600
CONFIG_ACTIVE_SCAN_DURATION=3
CONFIG_END_DEVICE_BIND_TIMEOUT=60
CONFIG_PAN_ID_CONFLICT_REPORT_THRESHOLD=2
CONFIG_REQUEST_KEY_TIMEOUT=0
CONFIG_APPLICATION_ZDO_FLAGS=0
CONFIG_BROADCAST_TABLE_SIZE=15
CONFIG_MAC_FILTER_TABLE_SIZE=2
CONFIG_SUPPORTED_NETWORKS=1
CONFIG_SEND_MULTICASTS_TO_SLEEPY_ADDRESS=0
CONFIG_ZLL_GROUP_ADDRESSES=0
CONFIG_ZLL_RSSI_THRESHOLD=216
CONFIG_MTORR_FLOW_CONTROL=1
CONFIG_RETRY_QUEUE_SIZE=16
CONFIG_NEW_BROADCAST_ENTRY_THRESHOLD=9
CONFIG_TRANSIENT_KEY_TIMEOUT_S=300
CONFIG_BROADCAST_MIN_ACKS_NEEDED=255
CONFIG_TC_REJOINS_USING_WELL_KNOWN_KEY_TIMEOUT_S=300
CONFIG_CTUNE_VALUE=140
CONFIG_ASSUME_TC_CONCENTRATOR_TYPE=1

(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> bellows -d com6 -b 115200 scan
Scanning channels 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
[EmberZigbeeNetwork(channel=11, panId=0x9837, extendedPanId=8b:71:0c:86:72:08:b5:6e, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 192, -52]
[EmberZigbeeNetwork(channel=15, panId=0x0e75, extendedPanId=be:ee:f7:fe:4e:16:0b:80, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 116, -71]
[EmberZigbeeNetwork(channel=15, panId=0xa126, extendedPanId=75:45:39:a6:05:e6:96:b0, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 172, -57]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 224, -44]
[EmberZigbeeNetwork(channel=15, panId=0x7fcb, extendedPanId=9c:11:ec:1a:66:fe:6e:1a, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 124, -69]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 248, -38]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 184, -54]
[EmberZigbeeNetwork(channel=15, panId=0xd337, extendedPanId=e5:f5:25:15:55:65:b5:05, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 172, -57]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 208, -48]
[EmberZigbeeNetwork(channel=15, panId=0x0e75, extendedPanId=be:ee:f7:fe:4e:16:0b:80, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 240, -40]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 124, -69]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 255, -35]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 212, -47]
[EmberZigbeeNetwork(channel=15, panId=0x2af0, extendedPanId=09:dc:84:ee:42:46:21:23, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 248, -38]
[EmberZigbeeNetwork(channel=20, panId=0xe758, extendedPanId=59:86:3e:50:b2:3a:1d:20, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 164, -59]
[EmberZigbeeNetwork(channel=20, panId=0xe758, extendedPanId=59:86:3e:50:b2:3a:1d:20, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 132, -67]
[EmberZigbeeNetwork(channel=20, panId=0xe758, extendedPanId=59:86:3e:50:b2:3a:1d:20, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 148, -63]
[EmberZigbeeNetwork(channel=20, panId=0xe758, extendedPanId=59:86:3e:50:b2:3a:1d:20, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 168, -58]
[EmberZigbeeNetwork(channel=20, panId=0xe758, extendedPanId=59:86:3e:50:b2:3a:1d:20, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 152, -62]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 136, -66]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 168, -58]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 164, -59]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 152, -62]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 192, -52]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 120, -70]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 72, -82]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 180, -55]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 140, -65]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 172, -57]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 192, -52]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 172, -57]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 96, -76]
[EmberZigbeeNetwork(channel=25, panId=0x010d, extendedPanId=a1:bd:76:32:f1:66:88:77, allowingJoin=<Bool.false: 0>, stackProfile=2, nwkUpdateId=0), 128, -68]
```
Zigpy is not working setting the port speed so its not go:
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> zigpy radio --baudrate 115200 ezsp com4 energy-scan
Usage: zigpy radio [OPTIONS] [ezsp|deconz|xbee|zigate|znp] PORT COMMAND
                   [ARGS]...
Try 'zigpy radio --help' for help.

Error: no such option: --baudrate
```
The command is patched from the example https://github.com/zigpy/zigpy-cli#reset-a-radio.
I was trying sending one leave command to one EZSP NCP last week with bellows but i was not getting it working but now its working great.
Perhaps _some one_ have fixing it and i was updating the install for testing the flasher.

PS: I running bellows / Zigpy in one virtual env without HA and have not defaut config or DB.

**Comment by puddly** [comment]
Perhaps you are running an old version? That exact command works for me.

**Comment by MattWestb** [comment]
Zigpy shall being up to date:
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> pip install zigpy update
Requirement already satisfied: zigpy in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (0.52.2)
Requirement already satisfied: update in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (0.0.1)
Requirement already satisfied: aiohttp in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (3.7.3)
Requirement already satisfied: yarl in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (1.6.3)
Requirement already satisfied: cryptography in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (3.4.7)
Requirement already satisfied: crccheck in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (1.0)
Requirement already satisfied: async-timeout in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (3.0.1)
Requirement already satisfied: importlib-resources in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (5.10.0)
Requirement already satisfied: voluptuous in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (0.12.1)
Requirement already satisfied: aiosqlite>=0.16.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (0.16.1)
Requirement already satisfied: pyserial-asyncio!=0.5 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from zigpy) (0.6)
Requirement already satisfied: style==1.1.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from update) (1.1.0)
Requirement already satisfied: typing_extensions>=3.7.2 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from aiosqlite>=0.16.0->zigpy) (3.7.4.3)
Requirement already satisfied: pyserial in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from pyserial-asyncio!=0.5->zigpy) (3.4)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from aiohttp->zigpy) (3.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from aiohttp->zigpy) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from aiohttp->zigpy) (20.3.0)
Requirement already satisfied: idna>=2.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from yarl->zigpy) (3.1)
Requirement already satisfied: cffi>=1.12 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from cryptography->zigpy) (1.14.6)
Requirement already satisfied: zipp>=3.1.0 in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from importlib-resources->zigpy) (3.10.0)
Requirement already satisfied: pycparser in c:\msys32\portainer\belloows\bellows-venv\lib\site-packages (from cffi>=1.12->cryptography->zigpy) (2.20)
```
Old Python ?
`Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0`

**Comment by puddly** [comment]
You may  have to do this to update zigpy-cli itself:

```bash
pip uninstall zigpy-cli
pip install git+https://github.com/zigpy/zigpy-cli  # if you have Git
pip install https://github.com/zigpy/zigpy-cli/archive/refs/heads/dev.tar.gz  # if you don't have Git
```

**Comment by MattWestb** [comment]
Now then not joined:
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> zigpy radio --baudrate 115200 ezsp com4 energy-scan
2022-12-07 20:54:11.599 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_SOURCE_ROUTE_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_INVALID_VALUE
2022-12-07 20:54:11.663 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
2022-12-07 20:54:11.725 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_ADDRESS_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
2022-12-07 20:54:11.929 MW-E3222 zigpy.application ERROR Couldn't start application
Traceback (most recent call last):
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy\application.py", line 132, in startup
    await self.initialize(auto_form=auto_form)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy\application.py", line 77, in initialize
    await self.load_network_info(load_devices=False)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\bellows\zigbee\application.py", line 207, in load_network_info
    await self._ensure_network_running()
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\bellows\zigbee\application.py", line 155, in _ensure_network_running
    raise NetworkNotFormed(f"Failed to init network: {init_status!r}")
zigpy.exceptions.NetworkNotFormed: Failed to init network: <EmberStatus.NOT_JOINED: 147>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\msys32\Portainer\belloows\bellows-venv\Scripts\zigpy.exe\__main__.py", line 7, in <module>
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy_cli\cli.py", line 19, in inner
    return loop.run_until_complete(cmd(*args, **kwargs))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy_cli\radio.py", line 178, in energy_scan
    await app.startup()
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy\application.py", line 132, in startup
    await self.initialize(auto_form=auto_form)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\zigpy\application.py", line 77, in initialize
    await self.load_network_info(load_devices=False)
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\bellows\zigbee\application.py", line 207, in load_network_info
    await self._ensure_network_running()
  File "C:\msys32\Portainer\belloows\bellows-venv\lib\site-packages\bellows\zigbee\application.py", line 155, in _ensure_network_running
    raise NetworkNotFormed(f"Failed to init network: {init_status!r}")
zigpy.exceptions.NetworkNotFormed: Failed to init network: <EmberStatus.NOT_JOINED: 147>
```
and formed network:
```
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> bellows -d com4 -b 115200 form -D .\zigbee.db
warning: Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
warning: Couldn't set EzspConfigId.CONFIG_SOURCE_ROUTE_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_INVALID_VALUE
warning: Couldn't set EzspConfigId.CONFIG_ADDRESS_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
(bellows-venv) PS C:\msys32\Portainer\belloows\bellows-venv> zigpy radio --baudrate 115200 ezsp com4 energy-scan
2022-12-07 20:55:31.754 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_SOURCE_ROUTE_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_INVALID_VALUE
2022-12-07 20:55:31.785 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
2022-12-07 20:55:31.926 MW-E3222 bellows.ezsp.protocol WARNING Couldn't set EzspConfigId.CONFIG_ADDRESS_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
Channel energy (mean of 1 / 5):
------------------------------------------------
 + Lower energy is better
 + Active Zigbee networks on a channel may still cause congestion
 + TX on 26 in North America may be with lower power due to regulations
 + Zigbee channels 15, 20, 25 fall between WiFi channels 1, 6, 11
 + Some Zigbee devices only join networks on channels 15, 20, and 25
 + Current channel is enclosed in [square brackets]
------------------------------------------------
 -  11      20.00%  ####################
 -  12      34.90%  ##################################
 -  13      34.90%  ##################################
 -  14      10.59%  ##########
 - [15 ]    35.69%  ###################################
 -  16      36.86%  ####################################
 -  17      24.71%  ########################
 -  18      36.08%  ####################################
 -  19      34.90%  ##################################
 -  20      34.90%  ##################################
 -  21      23.92%  #######################
 -  22      39.22%  #######################################
 -  23      30.20%  ##############################
 -  24      34.51%  ##################################
 -  25      22.35%  ######################
 -  26*     33.73%  #################################


Aborted!
```
So now its looks working OK !!

Great thanks for your great work !!!

**Comment by MattWestb** [comment]
PS: I have updating my Python in Windows 10 to 3.11 and installed Zigpy-CLI and its working out of the box :-)))))))

**Pull request merged**
